# Generated by Django 4.2.4 on 2024-05-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_tag_video_duration_subcategory_video_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="related_videos",
            field=models.ManyToManyField(
                blank=True, related_name="related_to", to="videos.video"
            ),
        ),
    ]
