# Generated by Django 4.2.4 on 2024-05-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0004_video_related_videos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="related_videos",
            field=models.ManyToManyField(blank=True, to="videos.video"),
        ),
    ]
